// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notespr.Data.AppDbContext;

#nullable disable

namespace Notespr.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250215135805_AddCategoryModel")]
    partial class AddCategoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notespr.Models.Entity.Category", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            DisplayOrder = 1,
                            Name = "LowPrior"
                        },
                        new
                        {
                            id = 2L,
                            DisplayOrder = 2,
                            Name = "MedPrior"
                        },
                        new
                        {
                            id = 3L,
                            DisplayOrder = 3,
                            Name = "HighPrior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
